/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginPhoneRouteImport } from './routes/login.phone'
import { Route as LoginGoogleRouteImport } from './routes/login.google'
import { Route as LoginFacebookRouteImport } from './routes/login.facebook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPhoneRoute = LoginPhoneRouteImport.update({
  id: '/login/phone',
  path: '/login/phone',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginGoogleRoute = LoginGoogleRouteImport.update({
  id: '/login/google',
  path: '/login/google',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginFacebookRoute = LoginFacebookRouteImport.update({
  id: '/login/facebook',
  path: '/login/facebook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login/facebook': typeof LoginFacebookRoute
  '/login/google': typeof LoginGoogleRoute
  '/login/phone': typeof LoginPhoneRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login/facebook': typeof LoginFacebookRoute
  '/login/google': typeof LoginGoogleRoute
  '/login/phone': typeof LoginPhoneRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login/facebook': typeof LoginFacebookRoute
  '/login/google': typeof LoginGoogleRoute
  '/login/phone': typeof LoginPhoneRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login/facebook' | '/login/google' | '/login/phone'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login/facebook' | '/login/google' | '/login/phone'
  id: '__root__' | '/' | '/login/facebook' | '/login/google' | '/login/phone'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginFacebookRoute: typeof LoginFacebookRoute
  LoginGoogleRoute: typeof LoginGoogleRoute
  LoginPhoneRoute: typeof LoginPhoneRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/phone': {
      id: '/login/phone'
      path: '/login/phone'
      fullPath: '/login/phone'
      preLoaderRoute: typeof LoginPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/google': {
      id: '/login/google'
      path: '/login/google'
      fullPath: '/login/google'
      preLoaderRoute: typeof LoginGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/facebook': {
      id: '/login/facebook'
      path: '/login/facebook'
      fullPath: '/login/facebook'
      preLoaderRoute: typeof LoginFacebookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginFacebookRoute: LoginFacebookRoute,
  LoginGoogleRoute: LoginGoogleRoute,
  LoginPhoneRoute: LoginPhoneRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
