/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginPhoneRouteImport } from './routes/login.phone'

const LoginPhoneRoute = LoginPhoneRouteImport.update({
  id: '/login/phone',
  path: '/login/phone',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login/phone': typeof LoginPhoneRoute
}
export interface FileRoutesByTo {
  '/login/phone': typeof LoginPhoneRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login/phone': typeof LoginPhoneRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login/phone'
  fileRoutesByTo: FileRoutesByTo
  to: '/login/phone'
  id: '__root__' | '/login/phone'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginPhoneRoute: typeof LoginPhoneRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login/phone': {
      id: '/login/phone'
      path: '/login/phone'
      fullPath: '/login/phone'
      preLoaderRoute: typeof LoginPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LoginPhoneRoute: LoginPhoneRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
